### ISSUE TITLE
Unnecessary semicolon inside QueueSizeDataProviderTest

### ISSUE THREAD

**Issue by PhilippKuhlmay** [tomasnorre/typo3-crawler-widget#11]
There is an unnecessary semicolon 
https://github.com/tomasnorre/typo3-crawler-widget/blob/7f50e27ffab561618b500bba76aef094dedcb381/Tests/Unit/Widgets/Provider/QueueSizeDataProviderTest.php#L20

**Comment by brotkrueml** [comment]
Resolved: https://github.com/tomasnorre/typo3-crawler-widget/commit/6f833e5229fb8c155bbca0cb3320ed71eecc9c62
