### ISSUE TITLE
Check and add Dependency for PHP 8.0 in composer.json and GitHub workflow

### ISSUE THREAD

**Issue by PhilippKuhlmay** [tomasnorre/typo3-crawler-widget#14]
As it is possible to install this extension with TYPO3 11, we should check if it is possible to install and run with PHP 8.0.
We also should add PHP 8.0 to the GitHub workflow.

If everything works, we should add the dependency to the composer.json file.

**Comment by brotkrueml** [comment]
TYPO3 11.0 is not defined as compatible with PHP 8.0, perhaps with 11.1. In my extensions/libraries I use "php >= 7.2" as a constraint to avoid a blocker for someone who wants to try it on a new PHP version. If there fails something I consider it as a bug which will be solved. This also takes the burden always to publish a new version when a  new PHP version is ready. Symfony did the same some months ago, it was a long discussion on Twitter about the pros and cons.

As TYPO3 11.0 is not compatible yet, you can't add PHP 8.0 to GitHub actions (as long as you don't want to configure some tricks like pretending another PHP version so the composer installation is successful).

Also keep in mind: If you do add a constraint like "php ^7.2" in composer.json, you should also add the constraint to ext_emconf.php: "php 7.2.0-7.4.99".
